=== kenanbanal/LBYCPF2_DailyTimeRecord/test XMLs/dtr.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="startOfWeekDate">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="isRest" type="xs:boolean"/>
													<xs:element name="isPresent" type="xs:boolean"/>
													<xs:element name="startTime" type="xs:time"/>
													<xs:element name="endTime" type="xs:time"/>
													<xs:element name="renderedHours" type="xs:integer"/>
													<xs:element name="otHours" type="xs:integer"/>
												</xs:sequence>
												<xs:attribute name="day" type="xs:date"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="date" type="xs:date"/>
								</xs:complexType> 
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:integer"/>
					</xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kenanbanal/LBYCPF2_DailyTimeRecord/test XMLs/after current date.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dtr.xsd">
		<employee id="1111">
			<startOfWeekDate date="2030-01-06">
				<date day="2030-01-07">
					<isRest>1</isRest>
					<isPresent>0</isPresent>
					<startTime>00:00:00</startTime>
					<endTime>00:00:00</endTime>
					<renderedHours>0</renderedHours>
					<otHours>0</otHours>
				</date>
				<date day="2030-01-08">
					<isRest>0</isRest>
					<isPresent>1</isPresent>
					<startTime>09:00:00</startTime>
					<endTime>18:00:00</endTime>
					<renderedHours>8</renderedHours>
					<otHours>0</otHours>
				</date>
				<date day="2030-01-09">
					<isRest>0</isRest>
					<isPresent>1</isPresent>
					<startTime>09:00:00</startTime>
					<endTime>18:00:00</endTime>
					<renderedHours>8</renderedHours>
					<otHours>0</otHours>
				</date>
				<date day="2030-01-10">
					<isRest>0</isRest>
					<isPresent>1</isPresent>
					<startTime>09:00:00</startTime>
					<endTime>18:00:00</endTime>
					<renderedHours>8</renderedHours>
					<otHours>0</otHours>
				</date>
				<date day="2030-01-11">
					<isRest>0</isRest>
					<isPresent>1</isPresent>
					<startTime>09:00:00</startTime>
					<endTime>18:00:00</endTime>
					<renderedHours>8</renderedHours>
					<otHours>0</otHours>
				</date>
				<date day="2030-01-12">
					<isRest>0</isRest>
					<isPresent>1</isPresent>
					<startTime>09:00:00</startTime>
					<endTime>18:00:00</endTime>
					<renderedHours>8</renderedHours>
					<otHours>0</otHours>
				</date>
			</startOfWeekDate>
		</employee>	
	</employees>
